# Generated by Django 4.2.2 on 2023-06-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_id_alter_favourite_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='author',
            new_name='user',
        ),
    ]
