# Generated by Django 4.2.2 on 2023-06-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tag_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
