# Generated by Django 4.2.2 on 2023-06-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name_plural': 'Тематики статьи'},
        ),
    ]
