# Generated by Django 4.2.2 on 2023-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_scope_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='tags', to='articles.article', verbose_name='Статьи'),
        ),
    ]
