# Generated by Django 4.2.2 on 2023-06-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_tag_articles_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
