# Generated by Django 4.2.2 on 2023-06-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_remove_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['tag'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
    ]
