# Generated by Django 4.2.2 on 2023-06-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['is_main', 'tag'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
    ]
