# Generated by Django 4.2.2 on 2023-06-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
