# Generated by Django 4.2.2 on 2023-06-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
